language: c
sudo: false

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install md5sha1sum; fi
  - source devtools/travis-ci/install.sh
  - ls
  - pip install .

test:
  - py.test -v
  - cd mbuild/examples
  - py.test test_examples.py -v

os:
  - osx
  - linux

env:
  matrix:
    - PYTHON_VERSION=2.7
    - PYTHON_VERSION=3.4
    - PYTHON_VERSION=3.5



