name: test-environment
channels:
- mosdef
- bioconda
- janschulz
- omnia
- defaults
dependencies:
- numpy
- scipy
- packmol=1.0.0
- nglview>=0.6
- oset
- parmed
- mdtraj
- foyer
# Testing Deps
- pytest >=3.0
- jupyter
- nbformat
- ipyext
- python-coveralls
- pytest-cov
